config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/events')
  resources :events
  get '/home', to: 'home#index'
  resources :attendances
  devise_for :users
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
      belongs_to :user
      has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
      has_many :users
      validates :email, presence: true
      validates :password, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances
  has_many :events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances or /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:stripe_customer_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/attendances/_attendance.html.erb
<div id="<%= dom_id attendance %>">
  <p>
    <strong>Stripe customer:</strong>
    <%= attendance.stripe_customer_id %>
  </p>

</div>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stripe_customer_id, style: "display: block" %>
    <%= form.text_field :stripe_customer_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Show this attendance", @attendance %> |
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendances</h1>

<div id="attendances">
  <% @attendances.each do |attendance| %>
    <%= render attendance %>
    <p>
      <%= link_to "Show this attendance", attendance %>
    </p>
  <% end %>
</div>

<%= link_to "New attendance", new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendance %>

<div>
  <%= link_to "Edit this attendance", edit_attendance_path(@attendance) %> |
  <%= link_to "Back to attendances", attendances_path %>

  <%= button_to "Destroy this attendance", @attendance, method: :delete %>
</div>

app/views/events/_event.html.erb
      <div id="<%= dom_id event %>">
        <p>
          <strong>Start date:</strong>
          <%= event.start_date %>
        </p>

        <p>
          <strong>Duration:</strong>
          <%= event.duration %>
        </p>

        <p>
          <strong>Title:</strong>
          <%= event.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= event.description %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= event.price %>
        </p>

        <p>
          <strong>Location:</strong>
          <%= event.location %>
        </p>
      </div>
    </div>
  </main>
</body>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Events</h1>

<div id="events">
  <% @events.each do |event| %>
    <%= render event %>
    <p>
      <%= link_to "Show this event", event %>
    </p>
  <% end %>
</div>

<%= link_to "New event", new_event_path %>

app/views/events/new.html.erb
<body data-turbo="false">
  <main class="container d-flex justify-content-center align-items-center">
    <div class="col-sm-4"> 
    <h2 class="display-6 fw-bold font-family-asgardxbold text-center my-5">NEW EVENT</h2> 
    
<%= render "form", event: @event %>
<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>

app/views/home/index.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </head>

  <body data-turbo="false">
  <header>
    <ul class="nav nav-pills nav-fill gap-1 p-1 medium bg-black rounded-5 shadow-sm" id="pillNav2" role="tablist" style="--bs-nav-link-color: var(--bs-white); --bs-nav-pills-link-active-color: var(--bs-black);">
      <li class="nav-item" role="presentation">
        <a class="nav-link nav-link fw-bold fs-6 text-start" id="home-tab2" href="<%= home_path %>" role="tab" aria-selected="true">EVENTBRITE</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="profile-tab2" href="<%= new_user_registration_path %>" role="tab" aria-selected="false">Sign up</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="log-tab2" href="<%= new_user_session_path %>" role="tab" aria-selected="false">Log in</a>
      </li>
     <li class="nav-item" role="presentation">
        <a class="nav-link" id="log-tab2" href="<%= new_event_path %>" role="tab" aria-selected="false">Create an event</a>
      </li>
     <li class="nav-item" role="presentation">
        <a class="nav-link" id="log-tab2" href="<%= root_path %>" role="tab" aria-selected="false">Event</a>
      </li>
    </ul>
  </header>
  <%= yield %>
</body>
</html>